// Dicționarul de etichete, copiat din app/index.html: un `camp` canonic nu apare fără nume.
export const ETICHETE = {
  administrare_cont:  ["Administrare cont",    "cât costă să ții contul deschis (de regulă pe lună)"],
  deschidere_cont:    ["Deschidere cont",      "comision plătit o singură dată, la deschidere"],
  inchidere_cont:     ["Închidere cont",       "comision la închiderea contului"],
  extras_de_cont:     ["Extras de cont",       "eliberarea unui extras pe hârtie sau la ghișeu"],
  interogare_sold:    ["Interogare sold",      "verificarea soldului (ATM, ghișeu, SMS)"],
  emitere_card:       ["Emitere card",         "comision la emiterea cardului"],
  reemitere_card:     ["Reemitere card",       "card nou după pierdere, furt sau expirare"],
  administrare_card:  ["Administrare card",    "abonamentul cardului (lunar sau anual)"],
  retragere_numerar:  ["Retragere numerar",    "scoaterea de bani de la ATM sau ghișeu"],
  transfer_credit:    ["Transfer trimis",      "plată ordonată de client către alt cont"],
  transfer_debit:     ["Debitare directă",     "plăți trase automat din cont (direct debit)"],
  incasare:           ["Încasare",             "bani primiți în cont din altă bancă"],
  modificare_anulare: ["Modificare / anulare", "schimbarea sau anularea unei plăți deja date"],
  documentar:         ["Operațiuni documentare", "acreditive, incasso, scrisori de garanție — în general pentru firme"],
  /* conceptele adăugate pe 24.09.2026 (vocabular.py, runda a cincea) */
  tranzactie_gambling:["Plăți la jocuri de noroc", "comisionul la comercianții de gambling, separat de plata obișnuită cu cardul"],
  caseta_valori:      ["Casetă de valori",     "închirierea unei casete sau a unui seif, pe an sau pe lună"],
  eliberare_document: ["Eliberare documente",  "adeverințe, confirmări de sold pentru audit, scrisori de bonitate, duplicate"],
  curierat_posta:     ["Curierat și poștă",    "trimiterea documentelor prin curier, poștă sau fax"],
  investigatie:       ["Investigații",         "cercetarea unei plăți sau a unei tranzacții, la cererea clientului"],
  miniextras_atm:     ["Miniextras la ATM",    "lista ultimelor tranzacții, tipărită la bancomat"],
  card_pierdut_furat: ["Card pierdut sau furat", "raportarea cardului pierdut sau furat, de regulă în străinătate"],
  inchidere_card:     ["Închidere card",       "comision la închiderea cardului"],
  recuperare_card:    ["Recuperare card",      "recuperarea cardului reținut de bancomat"],
  token:              ["Token",                "dispozitivul de autentificare: emitere, înlocuire, suplimentar"],
  activare_banking_distanta: ["Activare internet banking", "comision o singură dată, la activarea sau instalarea serviciului"],
  notificare_push:    ["Notificări push",      "alertele trimise în aplicația de mobil"],
  notificare_email:   ["Notificări e-mail",    "alertele trimise prin e-mail"],
  depunere_moneda:    ["Depunere monedă metalică", "depunerea de monede, separat de depunerea de bancnote"],
  neridicare_numerar: ["Numerar programat neridicat", "penalitatea pentru o sumă programată și neridicată"],
  imputernicire:      ["Împuterniciri",        "adăugarea unui împuternicit sau verificarea unei procuri"],
  verificare_semnatura: ["Verificare semnături", "verificarea semnăturilor autorizate"],
  terminal_pos:       ["Terminal POS",         "chiria sau instalarea unui terminal POS la comerciant"],
  acordare_credit:    ["Analiză și acordare credit", "comisionul de analiză a dosarului și de punere la dispoziție"],
  administrare_credit:["Administrare credit",  "comisionul lunar de administrare a creditului"],
  rambursare_anticipata: ["Rambursare anticipată", "comisionul la plata anticipată a creditului"],
  modificare_credit:  ["Modificări la credit", "acorduri pe garanție, prelungiri, servicii la cerere pe durata creditului"],
  evaluare_garantie:  ["Evaluare garanție",    "raportul de evaluare a imobilului adus în garanție"],
  neplata_credit:     ["Credit restant",       "comisioane pentru rate neplătite sau notificări de restanță"],
  garantare_credit:   ["Garantare credit",     "comisioane datorate fondului de garantare (FNGCIMM)"],
  inregistrare_garantie: ["Înregistrare garanție", "avize în registrul garanțiilor (RNPM/AEGRM), contracte de garanție"],
  plata_asigurare:    ["Plata asigurării",     "plata polițelor de asigurare cesionate în favoarea băncii"],
  asigurare_credit:   ["Asigurare la credit",  "costul asigurării de viață sau a imobilului, pe durata creditului"],
  asigurare_card:     ["Asigurare la card",    "asigurări opționale atașate cardului (călătorie, protecția rambursărilor)"],
  custodie_titluri:   ["Custodie titluri",     "păstrarea titlurilor de stat și a instrumentelor financiare"],
  tranzactionare_titluri: ["Tranzacții cu titluri", "decontare la bursă, piața primară și secundară a titlurilor de stat"],
  portabilitate_cont: ["Portabilitate cont",   "mutarea contului la altă bancă"],
  acces_lounge:       ["Acces lounge",         "intrarea în saloanele de aeroport, prin card"],
  nominala:           ["Dobândă nominală",     "rata anunțată, fără comisioane incluse"],
  dae:                ["DAE",                  "dobânda anuală efectivă — include și comisioanele"],
  marja_ircc:         ["Marjă peste IRCC",     "cât adaugă banca peste indicele de referință"],
  comision_procent:   ["Comision procentual",  "comision calculat ca procent din sumă"],
  euribor_valoare:    ["EURIBOR",              "indicele de referință pentru împrumuturi în euro"],
  rate_fara_dobanda:  ["Rate fără dobândă",    "numărul de rate oferite la 0%"],
  nume_produs:        ["Nume de produs",       "denumirea comercială, fără cifră atașată"],
};

export const etNume = c => (ETICHETE[c] || [String(c).replace(/_/g, " ")])[0];
export const etDesc = c => (ETICHETE[c] || [null, ""])[1] || "";
